---
name: CI

on:
  push:

jobs:
  function-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: 'https://github.com/tehioant/Dojo-cicd-devops-octo/tree/main/func-dojo-cicd-skool'
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm test