---
name: CI
on: push
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install package
        run: npm install
        working-directory: ./func-dojo-cicd-skool
      - name: test package
        run: npm test --outputFile=../reports/jest/areport${{ GITHUB_JOB }}
        working-directory: ./func-dojo-cicd-skool

  
# un com pour relancer un push