---
name: CI
on: push
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install package
        run: npm install
        working-directory: ./func-dojo-cicd-skool
      - name: test package
        run: npm test
        working-directory: ./func-dojo-cicd-skool
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: reports/jest/code-coverage.html

  
# un com pour relancer un push